### ISSUE TITLE
table 'xxxxxx.replays' doesn't exist

### ISSUE THREAD

**Issue by untuned** [Jumper251/AdvancedReplay#1]
the replays table doesn't exist

**Comment by Jumper251** [comment]
It should create a table on startup if everything is configured correct. Are there any other error messages?

**Comment by untuned** [comment]
Yeah:
`04.03 18:24:00 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes`

**Comment by Jumper251** [comment]
Looks like a limitation in your database a MySQL update or changing the character set might help.
It worked on my databases but I try to decrease the key length in the next update.

**Comment by untuned** [comment]
It's shared hosting, so I can't do anything about it.

**Comment by Jumper251** [comment]
If it is only caused by the length of the primary key I can fix it in the next update.

**Comment by untuned** [comment]
Alright, if you can that would be great.
