### ISSUE TITLE
Could not pass event SoaromaFlagEvent to Sacaddons v1.7.1

### ISSUE THREAD

**Issue by CitizenPrayer** [Jumper251/AdvancedReplay#103]
I'm receiving the following errors from AdvancedReplay. SAC manager told me to let you know here. 

![unknown (1)](https://user-images.githubusercontent.com/10674301/178575870-d318a222-76e3-41ee-b460-6cd80836b988.png)

**Comment by AERONIKHD** [comment]
Minecraft 1.19 is currently not supported.
