### ISSUE TITLE
Question: plugin functionality

### ISSUE THREAD

**Issue by Badvait** [Jumper251/AdvancedReplay#105]
Using ReplayMod is such a pain and I was wondering if this is a _complete_ alternative to it.

What I mean by that, is can this plugin record _all_ changes in the world? Including stuff like other entities, recording the world's block state at whatever exact time I need it to, tnt exploding, etc?

This would be such a massive help for making YouTube videos, but I don't know if it has all the features I need. It would save me tons of time, but if it can't record everything, I don't know if I can use it.

**Comment by Jumper251** [comment]
AdvancedReplay can record players, living entities, items and projectiles.
Block recording is currently limited to changes made by players. TNT will not work.
