### ISSUE TITLE
Class not a depend, softdepend or loadbefore

### ISSUE THREAD

**Issue by HandyHat** [Jumper251/AdvancedReplay#11]
Got this when starting a recording

`[Server thread/WARN]: [AdvancedReplay] Loaded class com.comphenix.protocol.events.PacketListener from ProtocolLib v4.5.1 which is not a depend, softdepend or loadbefore of this plugin.`

Paper 333
ProtocolLib 4.5.1
Advanced Replay 1.5.2

**Comment by Jumper251** [comment]
I added ProtocolLib as depend in the plugin.yml
