### ISSUE TITLE
BugReport/Info: Possible Correlation For "AntiCheat Replay" and "AdvancedReplay" not working properly. 

### ISSUE THREAD

**Issue by Hax100** [Jumper251/AdvancedReplay#112]
**Plugin Info:**
Using: `AntiCheatReplay-2.7.5.jar` AND `AdvancedReplay 1.8.2` AND `Dev Build ProtocolLib.jar Remote V: 4.8.0 Current V: 5.0.0-SNAPSHOT-b602`
**Server Info:**
`PaperMC-1.18.1.jar` Lobby Server connected to a `Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504 by md_5` Bungee Network along with `Geyser + Floodgate + ViaVersion-4.4.2.jar + ViaBackwards-4.4.2.jar`

**Main:**
i think i figured out this bug a bit more, so my alt uses hacks, AntiCheatReplay makes AdvancedReplay start recording, my alt is kicked, AntiCheatReplay makes AdvancedReplay save the replay recording, my admin account plays the replay, all i see is my alt standing there the whole replay :( . BUT if i make my alt join the server back, then play the replay, it replays perfectly! meaning there is some kind of issue with replaying offline players. 

**Notes:**
I was told by AntiCheatReplay support to contact AdvancedReplay support to get this issue resolved. 
You might have been aware of this bug but I was told you might not be aware of the offline correlation with this bug. 
Hopefully, you can get this bug resolved, thank you.

**Comment by Jumper251** [comment]
Are there any error messages?
What Minecraft version do you use to watch the replay?
Does this only happen in combination with AntiCheat Replay?

**Comment by Hax100** [comment]
> Are there any error messages? - @Jumper251 
Not from AntiCheatReplay and not from AdvancedReplay 

> What Minecraft version do you use to watch the replay? - @Jumper251 
Admin Account Watches Replay With: 1.19.2
Alt Account Hacks With: 1.19 

> Does this only happen in combination with AntiCheat Replay? - @Jumper251 
I just tested it:
admin user did "/replay start [alt-username]"
alt ran around
alt left the server and stayed out
admin user did "/replay play [alt-username]"
the replay works fine. 
so it did not matter that my alt was offline. 
so this offline bug correlation only happens when AntiCheat-Replay-plugin makes the replay. 
[i even tested my alt hacking and having AntiCheat-Replay-plugin make the replays AGAIN, then my admin account played the replay while my alt is an offline and the "frozen player issue due to offline alt occurring" as described in the first thing I said in this bug report thread happened again.]

**Comment by JustinDevB** [comment]
> Are there any error messages?
> What Minecraft version do you use to watch the replay?
> Does this only happen in combination with AntiCheat Replay?

I’m the AntiCheat Replay dev. 
I have not tested this, but I have successfully reviewed replays while a player is offline in the past. Every now and then I get a replay where the player doesn’t move.

All my code does is tell AdvancedReplay when to record, who to record, for how long, and what to name it.

Here are some links to my code to see if you have any suggestions or that might help you understand better.

My hook for Vulcan Anticheat: https://github.com/JustinDevB/AntiCheatReplay/blob/master/src/main/java/me/justindevb/anticheatreplay/listeners/AntiCheats/VulcanListener.java

ListenerBase, where I handle most of the logic for creating a replay:
https://github.com/JustinDevB/AntiCheatReplay/blob/master/src/main/java/me/justindevb/anticheatreplay/ListenerBase.java

**Comment by Jumper251** [comment]
The Anticheat Replay code should work, I am not sure what could cause this.
Maybe you can send me the broken Replay so I can take a look at it.
