### ISSUE TITLE
[Bug] Incompatability with DecentHolograms' Actions

### ISSUE THREAD

**Issue by Whitebrim** [Jumper251/AdvancedReplay#117]
When anybody on the server leaves replay (if it finishes or via /rp leave or via door item), all Actions on [DecentHolograms](https://www.spigotmc.org/resources/decentholograms-1-8-1-19-papi-support-no-dependencies.96927/)'s holograms stop working. It's not fixable by reloading replay or holograms plugin, only by full server replay.
Hologram's Actions are handling left, right clicks on holograms. They stop working for everybody on the server.  

I think it might be false entity detecting by AdvancedReplay plugin, but DecentHolograms' dev say:
> d0by — 15.11.2022 0:51
Seems like when the replay plugin unregisters its packet listener from ProtocolLib, it also unregisters the one DH uses. It shouldn't work that way and I don't think there is anything wrong with the plugin itself but that's what it appears to be. I don't really know how I would go about preventing this. I'm no expert at ProtocolLib whatsoever (I like using plain NMS instead) so I can't tell what the actual cause could be.
I just know that when DH didn't support ProtocolLib by using its packet listeners when it was on the server, it caused other issues.

**Comment by Jumper251** [comment]
AdvancedReplay only unregisters its own packet listeners. 
Maybe this is a bug with ProtocolLib.

Are there any error messages?
Do the actions work while watching the replay (before leaving)?

**Comment by Whitebrim** [comment]
> Are there any error messages?

No

> Do the actions work while watching the replay (before leaving)?

Yes

**Comment by Jumper251** [comment]
If it works while watching it is probably not caused by AdvancedReplay.
