### ISSUE TITLE
Error "Could not pass event PlayerInteractEvent to AdvancedReplay v1.8.2" in 1.19.3

### ISSUE THREAD

**Issue by LZMAShili** [Jumper251/AdvancedReplay#121]
Hi at the end of the year! I updated from Purpur-1.19.2 to Purpur-1.19.3-1876 and now replay is not working properly in AdvancedReplay and I can't even exit.
I'm attaching the logs so you can check them.
[errorlog.log](https://github.com/Jumper251/AdvancedReplay/files/10327432/errorlog.log)

**Comment by JustinDevB** [comment]
Can confirm this bug on 1.19.3

https://pastebin.com/X2J7LN5X

**Comment by Jumper251** [comment]
1.19.3 is now supported.
