### ISSUE TITLE
Cant exit out of replay on 1.8.3

### ISSUE THREAD

**Issue by WhyCarnage** [Jumper251/AdvancedReplay#127]
potential duplicate of #118   but it seems like i cant exit out of a replay when i view it. Their issue was on 1.8.2
steps
1. create replay
2. watch replay
3. try the leave item thingy
4. try to drag items into inventory or /kill 

Logs: https://mclo.gs/eqoaErN
protocolLib version: ProtocolLib v5.0.0-SNAPSHOT-b610
server ver: 1.19.2

**Comment by Jumper251** [comment]
Explanation in this issue #132
