### ISSUE TITLE
Replay stop incompatibilities

### ISSUE THREAD

**Issue by sxphirus** [Jumper251/AdvancedReplay#131]
Stopping a replay breaks some packet listeners on the following plugins;
- Artmap https://gitlab.com/BlockStack/ArtMap
- Oraxen https://github.com/oraxen/oraxen

To reproduce;
- Install the above plugin(s) with AdvancedReplay
- Run `/replay start`
- Run `/replay stop`
- Attempt to use either artmap canvas (drawing on the canvas) or break an oraxen furniture model, neither work. Both are fixed after reloading the respective plugins.

**Comment by Jumper251** [comment]
AdvancedReplay only removes its own packet listeners.
Are there any error messages.
