### ISSUE TITLE
Error not fixed "Could not pass event PlayerInteractEvent to AdvancedReplay v1.8.3"

### ISSUE THREAD

**Issue by ehamawy** [Jumper251/AdvancedReplay#132]
Still having this error, even though it was supposedly fixed in [this issue](https://github.com/Jumper251/AdvancedReplay/issues/121).
Running AdvancedReplay 1.8.3 with latest ProtocolLib dev build #2172
Record Replay > Save Replay > Play Replay
Player is not rendered, time doesn't advance, control items are put in inventory but are unclickable, and aren't removed on replay end.
[le epic logz.txt](https://github.com/Jumper251/AdvancedReplay/files/10928045/le.epic.logz.txt)

**Comment by Jumper251** [comment]
AdvancedReplay 1.8.3 does not work on 1.19.2. 
https://www.spigotmc.org/resources/advancedreplay-1-8-1-19.52849/updates
