### ISSUE TITLE
Start-up issue

### ISSUE THREAD

**Issue by ItzStormizn** [Jumper251/AdvancedReplay#134]
![image](https://user-images.githubusercontent.com/126072934/230757593-75f9a53c-f063-4793-bf60-7036ab3da35f.png)
![image](https://user-images.githubusercontent.com/126072934/230757620-03a6940a-7c5e-49d9-9a6b-539337fe4789.png)
I am getting the following errors in the console. Please help. One more error, it doesn't TP me to the map where i started recording. I am using it for BW and it doesnt tp me in the map

**Comment by Jumper251** [comment]
This looks like a custom version of AdvancedReplay, I can't provide support for that.
