### ISSUE TITLE
Player cannot leave replay

### ISSUE THREAD

**Issue by bipedd** [Jumper251/AdvancedReplay#136]
When trying to force them to run: /replay leave this error occurs, relogging does nothing, the items it gives also do nothing, they are stuck

Error when running command for that player https://pastebin.com/V7hqz0u6

doesn't happen to everyone but it happens sometime to certain players

**Comment by Jumper251** [comment]
Is there more to this error message?
Do you know what the difference is in the attempts where it does not work?
