### ISSUE TITLE
SQL-SyntaxError?

### ISSUE THREAD

**Issue by ForrestCGN** [Jumper251/AdvancedReplay#137]
Hallo,

i have the following Error in my log :

[14:31:50] [Craft Scheduler Thread - 18 - AdvancedReplay/INFO]: [AdvancedReplay] Successfully conntected to MySQL database
[14:31:50] [Craft Scheduler Thread - 18 - AdvancedReplay/WARN]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-mc' at line 1

Server : Paper 1.19.3
MySQL/MariaDB : 10.5.18-MariaDB-0+deb11u1 - Debian 11

**Comment by PriyeshTripathi** [comment]
It looks like there is an error in the SQL syntax of the query being executed by AdvancedReplay. The error message states that there is an error near '-mc' on line 1, which suggests that there may be an issue with the table name or column name.

One possible cause of this error is that the table or column name contains a hyphen or some other special character that is not allowed in SQL syntax. To fix this, you may need to rename the table or column using a name that is allowed in SQL syntax.

Another possible cause of this error is that there is a typo or mistake in the query being executed. Double-check the query to ensure that it is written correctly and that all keywords and syntax are used correctly.

You may also want to check the version of your MariaDB server and compare it with the syntax being used in the query to ensure that they are compatible.
