### ISSUE TITLE
Permissions in LuckPerms doesn't show correctly

### ISSUE THREAD

**Issue by Josh65-2201** [Jumper251/AdvancedReplay#163]
## Description
In LuckPerms no permissions show for replay until I search what ones are available in console then type them in game. Even after there a permission made for each letter of the real permission.
![image](https://github.com/Jumper251/AdvancedReplay/assets/26977075/424a126c-287a-4b94-8b88-394fbdc6bc6f)
![image](https://github.com/Jumper251/AdvancedReplay/assets/26977075/405eb977-b85c-4622-933e-f6079762c810)

## Steps to reproduce 
1. Download LuckPerms and replay
2. Start server
3. Open LuckPerms default catory
4. Type `replay`
5. See no permissions

## Logs
None

## Versions
Server: 1.20.1 Paper 196
Replay plugin: 1.8.5
LuckPerms plugin: commit 0a70e7a

**Comment by Jumper251** [comment]
Fixed in AdvancedReplay 1.8.7.
