### ISSUE TITLE
[BUG] "Unable to connect to MySQL database: Public Key Retrieval is not allowed."

### ISSUE THREAD

**Issue by TheModdersDen** [Jumper251/AdvancedReplay#166]
The title pretty much covers the issue. When I try to enable the MySQL storage mode for this plugin, it returns the error in the title. I have tired to fix this (with the following ideas/attempts), but to no avail:

1. Change the ```YAML``` config files values to be strings (add a ```'``` around the values required to connect to the server.
2. Verifying the URL, port, etc. is all correct.
3. [Turning it off and on again](https://www.youtube.com/watch?v=5UT8RkSmN4k) - IT Crowd Reference. 😉
4. Looking through the closed and open issues for potential solutions and duplicates.
5. Etc.

Any help/ideas would be greatly appreciated. I would love to not have to go and edit the source of your plugin, recompile it, and try it out on my own if there's a simple fix that I'm just oblivious to.

Thanks in advance,
//TheModdersDen

Also, attached to this issue is a link with the latest log from my server. 😄 

[Log here (GhostBin)](https://pst.innomi.net/paste/x95jc9nthkz5d2b3v3mx2bq3h7qqjfht)

Password is: `MC101`

**Comment by TheModdersDen** [comment]
Quick follow-up: A bit about my server:

* Its running PaperMC (1.20.4, the latest version at the time of writing)
* It has a _few_ plugins (I can send a list, if needed, as it is actually pretty well fleshed out with plugins)
* And I am running the server on a Windows 11 Pro tower.

Hopefully that information might clear up potential follow-up questions. :)

**Comment by Jumper251** [comment]
It looks like this can be fixed by adding another property to the MySQL connection.
I can add an option for that to the mysql.yml.

**Comment by TheModdersDen** [comment]
If you could, that would be awesome! 😎

**Comment by Jumper251** [comment]
In AdvancedReplay version 1.8.6 you can now change the MySQL connection properties.
The default will look something like this:

```
port: 3306
host: 'yourhost'
database: 'yourdb'
username: 'username'
password: 'password'
prefix: ''
properties:
- useSSL=false
- characterEncoding=latin1
```


In your case, adding `allowPublicKeyRetrieval=true` should fix the issue.

**Comment by TheModdersDen** [comment]
Awesome! I will test it out after my work today! 😃
