### ISSUE TITLE
[Repo Feature] Define standards for formatting and code style.

### ISSUE THREAD

**Issue by Nubebuster** [Jumper251/AdvancedReplay#171]
There are some issues with the project formatting that I think don't help with code review. Personally I let Intellij format the code so I don't have to worry about trivial things when writing the code. This helps improve the overall readability and makes the code look cleaner.

During my contribution I noticed many classes have more than one indentation style in one file. It also seems many contributions have not had any formatting. Therefore I think it's a good idea to choose some standards and put them in the README so that people know what to expect. My personal favorite is https://google.github.io/styleguide/javaguide.html
I wouldn't follow it on the dot but I think Intellij (mostly) complies with this standard at default settings.

**Comment by Jumper251** [comment]
Sounds like a good idea, I added some information for anyone who would like to contribute https://github.com/Jumper251/AdvancedReplay/blob/master/CONTRIBUTING.md
