### ISSUE TITLE
Missing Hurt Animation

### ISSUE THREAD

**Issue by PedroMPagani** [Jumper251/AdvancedReplay#173]
Hey, I'd like to contribute since i'll use it as well, i'm gonna be posting what I think it's missing from player actions and you can work on it together if you want :)

**Comment by Jumper251** [comment]
What version did you test this on? I think hurt animations broke for a couple of versions without me noticing but it should be fixed in Minecraft 1.21.

**Comment by PedroMPagani** [comment]
> What version did you test this on? I think hurt animations broke for a couple of versions without me noticing but it should be fixed in Minecraft 1.21.

I tested it on 1.20.6 with the latest branch

**Comment by Jumper251** [comment]
The new hurt animation packet is only used in 1.21 but it looks like 1.20 also needs it. I'll test it out, but it should be a simple change.

**Comment by PedroMPagani** [comment]
Gotcha, I implemneted it to 1.20.6 but I didn't know that it already had the function for the play damage effect
