### ISSUE TITLE
Block Effects (Particles)

### ISSUE THREAD

**Issue by PedroMPagani** [Jumper251/AdvancedReplay#175]
Are these already added? I am not seeing them if its with the .sendBlockChange instead of the .setType() or "breakNaturally"

**Comment by PedroMPagani** [comment]
https://github.com/user-attachments/assets/0e8ad79d-dcfc-4cad-990e-8a65addec8ef

Update on this, the effect/sound is handled with WORLD_EVENT, it seems on wiki.vg that id tends to change sometimes.

**Comment by Jumper251** [comment]
There might be an API way to do this, it worked before Minecraft 1.13 by sending the STEP_SOUND effect. Maybe that is updatable to newer versions.

**Comment by PedroMPagani** [comment]
Nowadays it's a world event packet. I managed to get this to work but it has to be done with this world event otherwise it's not triggered

**Comment by Jumper251** [comment]
Should be working again in the latest version.
