### ISSUE TITLE
Support S3 as a storage backend

### ISSUE THREAD

**Issue by gerolndnr** [Jumper251/AdvancedReplay#185]
To really use this system in an enterprise environment, the usage of S3 compatible storage would be great.

I will try to implement it myself and open a pull request when it's ready.

**Comment by gerolndnr** [comment]
I implemented it in my fork (https://github.com/gerolndnr/AdvancedReplay).

I used the `minio` sdk to access S3, because everything else would be too complicated.
Shading the sdk into the file would make the resulting file unnecessarily big, so I shaded `libby` (https://github.com/AlessioDP/libby) into the jar, which loads the `minio` sdk at runtime, but only, if the user enables S3 in the `config.yml`. 
Libby adds about 40kb to the final jar file. 

I think you could also load the PacketWrappers at runtime with libby, so they wouldn't be needed inside the jar, resulting in a even smaller file, but I haven't tested it yet.

Please tell me if you want me to open a pull request or if you think this would make more sense as a seperate 'extension' plugin and shouldn't be merged into the main project.

**Comment by Jumper251** [comment]
I think this could definitely be a useful feature for some users and if the large sdk only loads when it's needed I don't see any reason not to merge this into the main plugin.

A lot of the PacketWrappers are customized for different minecraft versions and not the default ones from ProtocolLib, so loading them would not work.

**Comment by gerolndnr** [comment]
Very cool, I opened a pull request: https://github.com/Jumper251/AdvancedReplay/pull/186
