### ISSUE TITLE
PacketEvents migration

### ISSUE THREAD

**Issue by HaHaWTH** [Jumper251/AdvancedReplay#188]
ProtocolLib is unfortunately no longer very active and the updates take longer and longer and unfortunately often no longer work satisfactorily. PacketEvents is another actively maintained packet processing library.

PacketEvents repository: https://github.com/retrooper/packetevents

It could be hard to migrate such a large project. But some bugs can be resolved by migration

**Comment by Jumper251** [comment]
PacketEvents looks promising and at some point I might consider switching. We already have an open issue for further discussion, #176
