### ISSUE TITLE
When world is not loaded or doesn't exist the plugin bug yourself

### ISSUE THREAD

**Issue by kingakis2** [Jumper251/AdvancedReplay#191]
hello, on my server we have temporal dungeon worlds and when user replay is on these dungeons when that world is deleted the plugin bug you if you use /replay play and you can't do anything until you restart the server

 it would be great if the plugin just detects that the world doesn't exist and just sends a message that the replay can't be loaded so the plugin don't just break
[after using replay play and the world doesn't exist.txt](https://github.com/user-attachments/files/17089999/after.using.replay.play.and.the.world.doesn.t.exist.txt)
[replay leave after replay play.txt](https://github.com/user-attachments/files/17090000/replay.leave.after.replay.play.txt)
[user that uses replay play leaving the server.txt](https://github.com/user-attachments/files/17090007/user.that.uses.replay.play.leaving.the.server.txt)

**Comment by Jumper251** [comment]
Should be improved in the newest version
