### ISSUE TITLE
permissions don't work fine

### ISSUE THREAD

**Issue by kingakis2** [Jumper251/AdvancedReplay#192]
im giving these permissions to a group and i don't want them to be able to use /replay delete but, they can't use any of those commands

giving to the group replay.command permission gives all permission including /replay delete for now im using replay.command on true and replay.command.delete on false and it works but, they should not work in this way right?

![image](https://github.com/user-attachments/assets/c26f3fa5-b2b6-45a4-aad5-fd2789f7765a)

**Comment by Jumper251** [comment]
I fixed a couple of things in the plugin.yml, the permissions should work now. 
Players will need the `replay.command` permissions as a baseline to execute the /replay command and more specific permissions like `replay.command.overview` or `replay.command.play` as needed.
