### ISSUE TITLE
Mob killing in replay

### ISSUE THREAD

**Issue by KhrysAK47** [Jumper251/AdvancedReplay#193]
If a mob is killed during the replay being saved, it does not save inside the replay.

**Comment by Jumper251** [comment]
I need some more information about the problem.

Does mob recording work in general and only the death is not recorded?
What are the Minecraft, AdvancedReplay and ProtocolLib versions you use on your server?

**Comment by KhrysAK47** [comment]
They work, however, if a mob is killed during the replay that is being saved, it does not appear in the replay at all (empty).

Paper 1.20.4, running AdvancedReplay v1.8.10 and ProtocolLib 5.2.0-SNAPSHOT-679

**Comment by Jumper251** [comment]
AdvancedReplay does not work well on 1.20.4. This should work once you update to 1.21 and the latest version of ProtocolLib.
