### ISSUE TITLE
ItemJoin incompatibility

### ISSUE THREAD

**Issue by SlimeDog** [Jumper251/AdvancedReplay#2]
Spigot 1.13.2
ProtocolLib 4.4.0-b425
Multiverse-Core 3.0.0-b761
Multiverse-Portals 3.0.0-b790
ItemJoin 5.0.4-b228
AdvancedReplay 1.3.3
Test server, with bleeding-edge plugins. I was the only player. I was OP, but also explicit _replay.*_ permissions granted. There is a single ItemJoin control in (0-based) inventory hotbar slot 8.

> /replay start x1 _playerName_

Recorded a track of myself
- Moved through MV portal to transport to a second MV world
- Used DeluxeMenus to transport to a third MV world
- Used DeluxeMenus to transport to the original world and location

> /replay stop x1

Replay file was saved.

> /replay play x1

Replay starts
- Replay controls are displayed
- I watch recorded version of myself move through MV portal
- I teleport to recorded version of myself, using AR controls
- Upon reaching the second world, the AR leave control is overwritten by the ItemJoin control, and I cannot leave the recording
- At that point, the AR controls are not linked to the AR system; they are just items in the inventory hotbar, and can be dropped

I disconnected and reconnected to the server, to try to regain control and leave the recorded session. That was probably successful, since the AR controls were not active, but the AR controls remained in the inventory, as items unrelated to AR.

During the entire session, no errors were reported in-game or in console/log. 

Feature request: Please implement _**/replay leave**_ as a command. See #3

**Comment by Jumper251** [comment]
I tested the steps with a similar setup and even though some of the Replay Items were overwritten the other ones remained working.
The Replay stopped automatically (after it finished) and removed the control Items. 
Usually your Items are also reset if you leave while watching a Replay.

You might need to configure ItemJoin so it doesn't overwrite your items after world change.

**Comment by SlimeDog** [comment]
The design requires that the ItemJoin item remain permanently in slot 8, so it must overwrite anything in that slot on world change. Possible solution feature request: support configuration of the slots occupied by the AR controls.

**Comment by Jumper251** [comment]
I might add configuration options for that together with some replay control commands in the next update.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by SlimeDog** [comment]
Thanks. Works perfectly.
