### ISSUE TITLE
Error when playing a replay that was started recording with 0 players on the server

### ISSUE THREAD

**Issue by Alex7892014** [Jumper251/AdvancedReplay#22]
Hey,

a get an error when playing a replay that was started with 0 players on the server.

That in my case happens because i start a replay directly via API when the server starts up.
I use the "add_new_players" config value also.

The error is because you directly use the data action key 0 which, dont exists when first starting a replay and players afterwards join.

![issuereplay1](https://user-images.githubusercontent.com/6545956/103579997-ab13bf80-4ed9-11eb-8952-42f269a9af04.png)

**Comment by Jumper251** [comment]
I noticed this too. This error should be fixed in the next version.
