### ISSUE TITLE
1.16. Buckets not supported

### ISSUE THREAD

**Issue by Alex7892014** [Jumper251/AdvancedReplay#23]
Hey,

the new buckets added in minecraft 1.16. are not implemented yet ant therefore dont work at all.

Bucket of Cod
Bucket of Salmon
Bucket of Pufferfish
Bucket of Tropical Fish

https://minecraft.gamepedia.com/Bucket_of_Fish

**Comment by Jumper251** [comment]
New items from after the item id update (1.13+) can only be recorded as air.
I have to rewrite the item recording to support all the new stuff.

**Comment by Jumper251** [comment]
Should be improved in 1.6.3.
