### ISSUE TITLE
Teleporting to a NPC causes armor to dissapear until a next inventory change.

### ISSUE THREAD

**Issue by penguintijn-nl** [Jumper251/AdvancedReplay#32]
Title says it all...

When I teleport to a NPC using the teleporter item in a replay causes the armor of the NPC to dissapear until the NPC's inventory changes or the NPC changes his hotbar slot.

**Comment by Jumper251** [comment]
That should not happen, which Minecraft version are you using?

**Comment by penguintijn-nl** [comment]
I'm using Spigot 1.8.8

**Comment by Jumper251** [comment]
Fixed in the latest update.
