### ISSUE TITLE
1.17.1 Compatability - Video Viewing Issue

### ISSUE THREAD

**Issue by JT14244** [Jumper251/AdvancedReplay#36]
I am playing on 1.17.1. I am able to use /replay fine. I can record replays. I can see info on the replay, but I am unable to rewatch the replay. See console errors below.

**/replay play test**
"[Fri, 16. Jul 2021 09:05:51 GMT WARN] Task #103277 for AdvancedReplay v1.6.4 generated an exception"

**/replay start test2**
"[Fri, 16. Jul 2021 09:06:13 GMT ERROR] [AdvancedReplay] Unhandled exception occured in onPacketSending(PacketEvent) for AdvancedReplay
[Fri, 16. Jul 2021 09:06:13 GMT ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy@3902a76d[
    a=[12227]
  ]
[Fri, 16. Jul 2021 09:06:17 GMT ERROR] [AdvancedReplay] Unhandled exception occured in onPacketSending(PacketEvent) for AdvancedReplay
[Fri, 16. Jul 2021 09:06:17 GMT ERROR] Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy@5eb9bb58[
    a=[12169]
  ]"

**Comment by QuanTrieuPCYT** [comment]
same issue here, waiting for a fix...

**Comment by Jumper251** [comment]
1.17.1 is now supported.
