### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by SlimeDog** [Jumper251/AdvancedReplay#4]
Spigot 1.13.2 final
AdvancedReplay 1.3.4

Please consider:
- Auto-track. If a recording is focused on a single player, it would be nice if replay followed the player through teleportations. Use case: I recorded a biome-tour, which traversed through 20 points in selected biomes, defined by [ServerTutorialPlus](https://www.spigotmc.org/resources/server-tutorial-plus.37741/). But AdvancedReplay does not follow the player in the recording, so I have to try to keep up with timed teleportations. Not ideal.
- **_/replay list_** should display date and time. Of course, columnar text would be best, with a little extra spacing to make it readable, and without the hyphens or "Date:" (the second block).
```
>replay list
[17:47:13 INFO]: [Replay] Available replays: (2) | Page: 1/1
[17:47:13 INFO]:  bt-1 - Date: 2019-05-21 17:27:08
[17:47:13 INFO]:  bt-547 - Date: 2019-05-21 17:35:09
```
```
>replay list
[17:47:13 INFO]: [Replay] Available replays: (2) | Page: 1/1
[17:47:13 INFO]: 2019-05-21 17:27:08   bt-1
[17:47:13 INFO]: 2019-05-21 17:35:09   bt-547
```
- Allow use of item _barrier_. Use case: I configured the leave item as
```
items:
  leave:
    id: BARRIER
```
Unfortunately, selecting it in the hotbar resulted in an error message (in red):
`You're not allowed to acquire Barrier.`

**Comment by Jumper251** [comment]
I will update the /replay list command and consider the Auto-track suggestion not sure if I will add it.

Also tested the Barrier item and it works for me, maybe another plugin is blocking it?

**Comment by SlimeDog** [comment]
Thanks.

WRT Barrier: Yep...WorldGuard configuration.
