### ISSUE TITLE
Items are real

### ISSUE THREAD

**Issue by JustinDevB** [Jumper251/AdvancedReplay#45]
If a recording captures a player throwing items on the ground and is then played back it shows the items being thrown on the ground. These are real items that get thrown onto the ground and anyone can pick them up.

Possible solution is to tag the items with a meta data and then listen to https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityPickupItemEvent.html

and check if the metadata matches and cancel the pickup. Also add the items to a list to be despawned when the replay ends.

**Comment by Jumper251** [comment]
Should be fixed now.
