### ISSUE TITLE
some entities aren't recorded correctly

### ISSUE THREAD

**Issue by PATXS** [Jumper251/AdvancedReplay#50]
tested on a fresh install of Paper 1.17.1-327 with the latest ProtocolLib (4.7.0) and AdvancedReplay 1.7, no other plugins

when using the option to record entities, some mobs (short for mobiles) either do not show up in the recording entirely or they show as different mobs. this happens every time, i have recorded videos to demonstrate ([me spawning the mobs in in real time](https://cdn.discordapp.com/attachments/454378929113792512/898449399456346112/advancedreplay1.mp4) vs [me watching the replay](https://cdn.discordapp.com/attachments/454378929113792512/898457449277820938/advancedreplay2.mp4)).

i've made a list of all the mobs i found to be bugged:

[original mob on the left, appeared mob on the right]
Husk = Evoker
Magma cube = Parrot
Pufferfish = Pig
Sheep = (none/invisible)
Shulker = (none/invisible)
Silverfish = (none/invisible)
Ravager = Pig
Skeleton = (none/invisible)
Slime = (none/invisible)
Skeleton horse = (none/invisible)
Salmon = Pig
Rabbit = Witch
Spider = (none/invisible)
Squid = Trader llama
Stray = Blaze
Strider = Pig
Zoglin = Pig
Zombie = (none/invisible)
Zombie horse = Fox
Zombie villager = (none/invisible)
Zombie piglin = Mule

**Comment by Jumper251** [comment]
Should be fixed now.
