### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by srnyx** [Jumper251/AdvancedReplay#55]
Getting this on server start: https://paste.srnyx.xyz/xibulosora.properties

**Comment by Jumper251** [comment]
I need some information:

- Which server software/version are you using?
- What is your version of AdvancedReplay?
- Is there anything specific I can do to reproduce this issue?

**Comment by srnyx** [comment]
> Which server software/version are you using?

Purpur 1.17.1

> What is your version of AdvancedReplay?

1.7

> Is there anything specific I can do to reproduce this issue?

https://paste.srnyx.xyz/duziwikiqe.yaml

**Comment by Jumper251** [comment]
Do you always get this error while recording?

**Comment by srnyx** [comment]
> Do you always get this error while recording?

Doesn't seem like it, no

**Comment by Jumper251** [comment]
Should be fixed now.
