### ISSUE TITLE
chat not show

### ISSUE THREAD

**Issue by deboi238** [Jumper251/AdvancedReplay#56]
when im testing/ using it the chat stuff wont show up

**Comment by Jumper251** [comment]
I need some information:

- Which server software/version are you using?
- What is your version of AdvancedReplay?
- I need your config.yml

**Comment by deboi238** [comment]
> I need some information:
> 
> * Which server software/version are you using?
> * What is your version of AdvancedReplay?
> * I need your config.yml

founded the problem, it was not enabled via config. but thx for the help
