### ISSUE TITLE
Feature request /replay startime <player> <seconds>

### ISSUE THREAD

**Issue by TunanaX** [Jumper251/AdvancedReplay#59]
Feature request
/replay startime <player> <seconds>
Eg:
/replay startime playerX 5s #after 5 seconds will automatically stop playback and save
D:\Server\Paper1.12.2\plugins\AdvancedReplay\replays
playerX-day-month-year-hour-minute-second.replay
#day-month-year-hour-minute-second = return real time after stop

I think a lot of server admins will like this.
I personally use it for the anti-hack plugin NoCheatPlus
Hope you can add it <3

**Comment by Jumper251** [comment]
Added in 1.7.1

You can now use `/Replay start :15` to start a replay with a random name that will stop after 15 seconds.
