### ISSUE TITLE
1.18 release?

### ISSUE THREAD

**Issue by IronicDeGawd** [Jumper251/AdvancedReplay#60]
Love the plugin, hope it updates soon!
Doesnt work on 1.18 currently.
https://pastebin.com/jxWKA3t3

**Comment by voidpls** [comment]
+1

**Comment by QuanTrieuPCYT** [comment]
yeah same thing, waiting for the thing to be updated

**Comment by Jumper251** [comment]
1.18 is now supported.

**Comment by QuanTrieuPCYT** [comment]
yo thanks lel
