### ISSUE TITLE
placed in replay blocks become real

### ISSUE THREAD

**Issue by E4zily** [Jumper251/AdvancedReplay#61]
the plugin has became really buggy itself. i play the replay, and the blocks that the player has placed become real and other people can walk on them. also, it does not hide real people while watching the replay. it would be amazing if this replay would create a new world without anything but the player.

**Comment by E4zily** [comment]
also, after the replay is done, there is an invisible entity that i can hit

**Comment by Jumper251** [comment]
You can hide other players by setting ` hide_players: true` in the config.yml.

There are two config options for block changes:
`reset_changes: true` this will reset block changes after the replay.
` real_changes: true` this will show fake block changes to the player watching the replay.

What kind of entity is invisible and how do you hit it?

**Comment by E4zily** [comment]
sorry for the long delay, just checked now:

after the replay is done, at the spot where the player disappears, if i hit that spot, there seems to be an invisible entity

**Comment by Jumper251** [comment]
How do you know that there is an invisible entity?
