### ISSUE TITLE
Q: How to get an instance of the API?

### ISSUE THREAD

**Issue by kz-n** [Jumper251/AdvancedReplay#62]
I am looking to integrate the ReplayAPI in my project although I am confused as to how exactly I would get an instance of it.

EDIT:
I am aware `ReplayAPI#getInstance` exists, With "how exactly I would get an instance of it." I meant that.

**Comment by Jumper251** [comment]
You already know the method to get an instance of the ReplayAPI, I am not sure what your question is.

**Comment by kz-n** [comment]
Sorry if I'm missing something, but how is one supposed to get an instance of the ReplayAPI in their own plugin?

**Comment by Jumper251** [comment]
You have to add the jar to your project and then you should be able to access the ReplayAPI class.

**Comment by daniel071** [comment]
@kz-n If want to see examples of how the api is implemented in other plugins, feel free to look at the source code of these plugins:
- https://github.com/daniel071/sacaddons
- https://github.com/JustinDevB/VulcanReplay
