### ISSUE TITLE
Issue: Replayed players/npcs staying put after a replay

### ISSUE THREAD

**Issue by bipedd** [Jumper251/AdvancedReplay#68]
![image](https://user-images.githubusercontent.com/77213949/147613237-88806942-05a6-4fb2-8b98-7013ced85940.png)

Alright, this is weird, I noticed that the NPCs stay in the location the players were at when the replay first starts, but if you teleport to the NPC via the compass and keep on doing so you can easily see that they are moving but the NPC is not, I'm unsure why I'm getting this issue. Those stay even after a replay ends but when I restart the server they disappear. Seems that when they're un-rendered they disappear.

**Comment by Jumper251** [comment]
Are there any error messages?
Which Minecraft version is your server on?
Does this always happen or just sometimes?

**Comment by TheDeafCreeper** [comment]
I'm having the same issue, with it happening about half the time, and there's no error messages.

Server is running git-Paper-402 (MC: 1.17.1)
Plugin is version 1.8

**Comment by bipedd** [comment]
> Are there any error messages? Which Minecraft version is your server on? Does this always happen or just sometimes?

No error messages
The server version is 1.18.1 Paper-110
Plugin version 1.8

**Comment by TheDeafCreeper** [comment]
Also idk if this happens for @bipedd, but when the NPC exists even outside of a replay it prevents me from seeing the real player.

**Comment by bipedd** [comment]
> Also idk if this happens for @bipedd, but when the NPC exists even outside of a replay it prevents me from seeing the real player.
Yeah

**Comment by bipedd** [comment]
> Also idk if this happens for @bipedd, but when the NPC exists even outside of a replay it prevents me from seeing the real player.

Yup.

**Comment by bipedd** [comment]
Any update?

**Comment by Jumper251** [comment]
I think I found the problem, it should be fixed in the next update.

**Comment by bipedd** [comment]
I still encounter this issue, any ETA on when the release where this is fixed will be out?

**Comment by bipedd** [comment]
https://user-images.githubusercontent.com/77213949/157556409-01dbedd8-d05a-410b-a6de-d2e0e3c8483c.mp4

Video ^

**Comment by Jumper251** [comment]
Should be fixed now.
Let me know if you still have the problem.
