### ISSUE TITLE
ConcurrentModificationException: null

### ISSUE THREAD

**Issue by nicuch** [Jumper251/AdvancedReplay#7]
https://gist.github.com/nicuch/009720030da1f831a0c4d630e0c37bfd
I got this error in the console, when there was no record.
https://github.com/Jumper251/AdvancedReplay/blob/master/src/me/jumper251/replay/replaysystem/recording/Recorder.java#L87
I sometimes ask myself why people don't update their java... and still support old Java 6 methods like Iterator. The List<?> itself is already an iterator in java 7. Please for the sake of less errors, drop support for java under version 8.

**Comment by nicuch** [comment]
Well, I've tried to put my nose under your plugin code, and mostly looks like a piece of garbage I just put on my server (look great tbh). I've tried to change some things, but using mostly deprecated/removed code from one version to another is a bad idea and I couldn't do it in the time I have left for today. You, and people in general, should understand that from 1.13 WE NO LONGER HAVE IDS FOR ITEMS. Material API has changed, and bugs can occur because of that.
I've done some of my things, under a fork (https://github.com/nicuch/AdvancedReplay) like adding a maven, updating some staff to Java 8 standards, changed bad codding, removed unnecessary things...

**Comment by Jumper251** [comment]
I am trying to keep the plugin compatible between 1.8 and 1.15 additionally Materials are saved with their ids in the Replay so I still need that.

I took a look at the changes and in between some insults it seemed like mostly formatting changes. The updates to the Java 8 syntax will be useful for the next update.
I don't really understand why you changed MaterialBridge https://github.com/nicuch/AdvancedReplay/blob/e0e7a3ac4fa863f81a41504dac7e8539c174b081/src/main/java/me/jumper251/replay/utils/MaterialBridge.java

**Comment by nicuch** [comment]
That was a last thing I changed before I gave up, and because I used Spigot 1.15.1 as dependency, the id getter from Material was removed, so I nulled it. To read your code I also formated the code to IntelliJ standards and that shouldn't have been the point. The Java 8 was the main point in those changes, and the removal of ids (and that's very wrong to still use them in 1.13+).
