### ISSUE TITLE
player does not move

### ISSUE THREAD

**Issue by kforbro** [Jumper251/AdvancedReplay#71]
If you turn on the saved replay, the player does not move. Paper 1.12.2
https://youtu.be/VkDMDS-WPBo

**Comment by Jumper251** [comment]
Are there any error messages?

**Comment by kforbro** [comment]
https://www.toptal.com/developers/hastebin/decivemede.rb

other than that, there are no errors in logs.

**Comment by Jumper251** [comment]
Is movement sometimes working or always broken?
Are you sure the player moved when recorded?

**Comment by kforbro** [comment]
movement always broken. yes, I'm sure. the video also shows that he was breaking blocks

**Comment by Jumper251** [comment]
Can you do /replay info <Name>, hover over Recorded data and make a screenshot?

**Comment by kforbro** [comment]
![image](https://user-images.githubusercontent.com/39985355/148410460-765f88d6-b801-42b1-af64-e6dccaf05800.png)

**Comment by Jumper251** [comment]
Can you send me the replay and the name of the worlds that were used?

**Comment by kforbro** [comment]
[8bitYT12-baritone-2022-01-05.279.replay.zip](https://github.com/Jumper251/AdvancedReplay/files/7829418/8bitYT12-baritone-2022-01-05.279.replay.zip)
world

**Comment by Jumper251** [comment]
Do you join the server with a different version than 1.12?

**Comment by kforbro** [comment]
Yes, I'm joining from 1.18. Does it matter?

**Comment by Jumper251** [comment]
There can be problems with plugins like ViaVersion, try to join with a version below 1.15 when watching replays.

**Comment by kforbro** [comment]
logged in from 1.12.2, everything is fine, thank you
