### ISSUE TITLE
Feature Request: Option to record all entities

### ISSUE THREAD

**Issue by JustinDevB** [Jumper251/AdvancedReplay#78]
As the title says, please consider adding a config option to record all entities. Or at least add support in the API to allow developers to include which entities they specifically want to record. Something similar to how we can supply a list of players to record.

**Comment by Jumper251** [comment]
The plugin is currently able to record players, living entities, projectiles and items.
Which entities do you want to record?

**Comment by JustinDevB** [comment]
I just tested it with 10 zombies around me. Even with entities enabled in the config none of them showed up in the replay.

**Comment by Jumper251** [comment]
On which Minecraft version did you test this?
