### ISSUE TITLE
I don't see the movement of the players

### ISSUE THREAD

**Issue by NockyCZ** [Jumper251/AdvancedReplay#89]
Please, how i can fix this?
https://medal.tv/games/minecraft/clips/gpJpXshDdJFbl/d1337XH5rh8J?invite=cr-MSxkT3MsNDYyNzAxMDAs

I cant see players movement

**Comment by Jumper251** [comment]
Maybe similar to this issue #71.

**Comment by NockyCZ** [comment]
Yes, thats a same problem, thanks :)
