### ISSUE TITLE
Overwrite replays

### ISSUE THREAD

**Issue by A5H73Y** [Jumper251/AdvancedReplay#96]
Hi, I'm the creator of the Parkour plugin and I hoped I could document how to integrate my plugin with AdvancedReplay to allow the Player to capture and replay their best time.

I initially got it working by running the following commands during Parkour's different events:
* Joining a Course: `replay start %PLAYER%-%COURSE% %PLAYER%`
* Leaving the Course / not beating their best: `replay stop %PLAYER%-%COURSE% -nosave`
* Achieving their best time: `replay stop %PLAYER%-%COURSE%`

This works the first time they complete, however a problem quickly appears when you try to join the Course again it says  "that the Replay already exists". Damn.

Then I tried to incorporate adding a timestamp to the replay name when it starts recording so it will always be a new recording; however another issue appears in that I now have no way to get the name of the recording at the point I need to save / discard them. Damn.

Completely out of options I am here to ask for support for you to either:
* Let me potentially overwrite existing replays when I want, or discard and keep the old one 
* Let me contextually stop the recording somehow, either by the Player name or some other method

Hope you are able to help, would be really cool to get this working well.

**Comment by Jumper251** [comment]
Hi,

would another option for the stop command like `-overwrite` or `-force` fix the problem?

So the command would be for example `replay stop %PLAYER%-%COURSE% -force`

**Comment by A5H73Y** [comment]
Thanks for responding.
I believe the issue lies with the starting of a replay recording that is not possible because it already exists.

So it would be nice to remove that limitation, but then have the option to overwrite the replay or discard that overwrite and retain the original if that makes sense.

The flow goes something like this, player "A5H73Y" joins course "example"
1) I join the course and it starts recording replay "A5H73Y-example" and I finish by best (only) time, the replay gets saved
2) I join the same course and it starts recording replay "A5H73Y-example", however this time I don't beat my best time so the new replay is discarded (keeping my previous best replay)
3) I join the same course and it starts recording replay "A5H73Y-example", this time I do best my best time so the new replay overwrites my old replay.

I basically want the ability to view each Player's best ever time, and store nothing else.

**Comment by Jumper251** [comment]
I will remove the limitation in the replay start command, so that you can use `/replay stop <Name>` to create new Replays, `/replay stop <Name> -nosave` to discard the recording and `/replay stop <Name> -force` to overwrite it.

**Comment by A5H73Y** [comment]
Awesome, thank you.
As long as the "-force" flag would still work even if the recording didn't already exist, and it more of a flag for "ignore validation" etc.

**Comment by Jumper251** [comment]
Added in 1.8.2
