### ISSUE TITLE
Dying when replaying cause the control items to drop into the ground

### ISSUE THREAD

**Issue by akiyuee** [Jumper251/AdvancedReplay#97]
Videos showcasing the bug:
[^1](https://cdn.discordapp.com/attachments/873855865474670623/983042583284568174/2022-06-05_23-17-50.mp4) [^2](https://cdn.discordapp.com/attachments/873855865474670623/983018960972816384/2022-06-05_14-13-24.mp4)

Steps to replicate this bug:
1. Enter a replay.
2. Die.
3. Reconnect 
4. Get the items that are dropped on the ground.

![image](https://user-images.githubusercontent.com/67498765/172060267-09bf18f6-bbfd-4360-aca5-1f376acc0288.png)

Best regards,
Akiyue.

**Comment by Jumper251** [comment]
Should be fixed now.
