### ISSUE TITLE
Replay have only 0 second

### ISSUE THREAD

**Issue by tudubucket** [Jumper251/AdvancedReplay#98]
I use AntiCheat Replay to replay the hackers (https://www.spigotmc.org/resources/anticheat-replay.97845/), it's automatically save the replay about the hacker's movement but these replay have only 0 second, is there any way to solve this probem

And yea i have told this to AntiCheat Replay support and they said that it's a AdvancedReplay problems

Attachment:
https://streamable.com/eb69e5
https://streamable.com/141mu2

**Comment by Jumper251** [comment]
Can you do /replay info [Name], hover over Recorded data and make a screenshot?

**Comment by tudubucket** [comment]
Sorry for the late reply

![image](https://user-images.githubusercontent.com/106295287/172845702-70e7fef6-3d73-47e1-86ff-8578c7135fd8.png)

**Comment by tudubucket** [comment]
I just accidently hit on close button lol

**Comment by Jumper251** [comment]
Does it work if you manually start and stop replays?
`/replay start <Name>`
`/replay stop <Name>`
`/replay play <Name>`

**Comment by tudubucket** [comment]
hmm they just told me this

![IMG_20220610_000503](https://user-images.githubusercontent.com/106295287/172904813-57f92cc8-11bd-4b6d-98aa-82c51313a1cd.jpg)
![IMG_20220610_000756](https://user-images.githubusercontent.com/106295287/172904831-0a9cd15b-e621-4afe-87dd-dedc5c6a72b7.jpg)

**Comment by tudubucket** [comment]
and i saw this (it's not a reply to me)
![IMG_20220610_000815](https://user-images.githubusercontent.com/106295287/172905433-3d32eb4b-8dcd-458f-8bc7-2f2a27acb6a9.jpg)

**Comment by Jumper251** [comment]
Is every replay from AntiCheat Replay 0 seconds?
Are there any error messages?

**Comment by tudubucket** [comment]
Yes, every replay from AntiCheat Replay is 0 seconds
There are no error messages

This is a log for 1 replay 
`[01:59:31] [pool-103-thread-1/INFO]: [AntiCheatReplay] Starting recording of player: huyptnh300410
[02:01:31] [Craft Scheduler Thread - 2255 - AntiCheatReplay/INFO]: [AntiCheatReplay] Saving recording of attempted hack...
[02:01:31] [Craft Scheduler Thread - 2255 - AntiCheatReplay/INFO]: [AntiCheatReplay] Saved as: huyptnh300410-flight-2022-06-11
[02:01:31] [Craft Scheduler Thread - 2220 - AntiCheatReplay/INFO]: [AntiCheatReplay] Sending WebHook request...
[02:01:32] [Craft Scheduler Thread - 2220 - AntiCheatReplay/INFO]: [AntiCheatReplay] Webhook sent!`

But somehow it worked after serveral server restart :d 
Thanks for your fast support!

![image](https://user-images.githubusercontent.com/106295287/173171613-1509c900-a86a-42da-bf82-f93ee17dc44a.png)
![image](https://user-images.githubusercontent.com/106295287/173171604-275e57ef-7bae-427b-bb7e-56e048ed94fe.png)
